const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),overlay=document.querySelector("#overlay"),startButton=document.querySelector("#start-button"),scoreEl=document.querySelector("#score"),bestEl=document.querySelector("#best");
let W=canvas.width,H=canvas.height;const keys=new Set();let game,frame,lastTime=0;
const stars=()=>Array.from({length:85},()=>({x:Math.random()*W,y:Math.random()*H,size:Math.random()*2.2+.4,speed:Math.random()*75+35}));
function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const oldW=W;H=720;W=Math.max(320,Math.round(H*rect.width/rect.height));canvas.width=W;canvas.height=H;if(game&&oldW){const scale=W/oldW;game.player.x*=scale;game.rocks.forEach(item=>item.x*=scale);game.shards.forEach(item=>item.x*=scale);game.stars.forEach(item=>item.x*=scale)}if(game&&!game.running)draw()}
function reset(){game={running:true,score:0,spawn:0,shard:1,player:{x:W/2,y:H-95,width:38,height:52},rocks:[],shards:[],stars:stars()};scoreEl.textContent="000000"}
function start(){cancelAnimationFrame(frame);reset();overlay.classList.add("hidden");lastTime=performance.now();frame=requestAnimationFrame(loop)}
function end(){game.running=false;const score=Math.floor(game.score),best=Math.max(Number(localStorage.getItem("stellar-drift-best")||0),score);localStorage.setItem("stellar-drift-best",best);bestEl.textContent=String(best).padStart(6,"0");overlay.querySelector("h2").textContent="Drift ended — "+score+" points";overlay.querySelector("p").textContent="The void is calling. Ready for another run?";startButton.textContent="Try again →";overlay.classList.remove("hidden")}
function hit(a,b){return a.x-a.width/2<b.x+b.width/2&&a.x+a.width/2>b.x-b.width/2&&a.y-a.height/2<b.y+b.height/2&&a.y+a.height/2>b.y-b.height/2}
function update(dt){const p=game.player,dir=(keys.has("ArrowRight")||keys.has("d")?1:0)-(keys.has("ArrowLeft")||keys.has("a")?1:0);p.x=Math.max(32,Math.min(W-32,p.x+dir*360*dt));game.score+=dt*12;game.spawn-=dt;game.shard-=dt;
  if(game.spawn<=0){const size=24+Math.random()*34;game.rocks.push({x:30+Math.random()*(W-60),y:-45,width:size,height:size,speed:210+Math.random()*150,angle:0});game.spawn=Math.max(.28,.82-game.score/1700)}
  if(game.shard<=0){game.shards.push({x:30+Math.random()*(W-60),y:-30,width:22,height:22,speed:190});game.shard=1.1+Math.random()*1.5}
  game.stars.forEach(s=>{s.y+=s.speed*dt;if(s.y>H){s.y=0;s.x=Math.random()*W}});game.rocks.forEach(r=>{r.y+=r.speed*dt;r.angle+=dt*2});game.shards.forEach(s=>s.y+=s.speed*dt);
  if(game.rocks.some(r=>hit(p,r)))return end();game.shards=game.shards.filter(s=>{if(hit(p,s)){game.score+=100;return false}return s.y<H+30});game.rocks=game.rocks.filter(r=>r.y<H+60);scoreEl.textContent=String(Math.floor(game.score)).padStart(6,"0")}
function draw(){const gradient=ctx.createRadialGradient(W/2,H/2,10,W/2,H/2,H);gradient.addColorStop(0,"#352173");gradient.addColorStop(1,"#0d091e");ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);ctx.fillStyle="white";game.stars.forEach(s=>{ctx.globalAlpha=.35+s.size/4;ctx.fillRect(s.x,s.y,s.size,s.size*2)});ctx.globalAlpha=1;
  game.shards.forEach(s=>{ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.PI/4);ctx.shadowBlur=16;ctx.shadowColor="#4dd6a4";ctx.fillStyle="#4dd6a4";ctx.fillRect(-8,-8,16,16);ctx.restore()});
  game.rocks.forEach(r=>{ctx.save();ctx.translate(r.x,r.y);ctx.rotate(r.angle);ctx.fillStyle="#ff4e91";ctx.strokeStyle="#18132a";ctx.lineWidth=5;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rad=r.width/2*(i%2?.76:1),x=Math.cos(a)*rad,y=Math.sin(a)*rad;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()});
  const{x,y}=game.player;ctx.save();ctx.translate(x,y);ctx.shadowBlur=18;ctx.shadowColor="#ffd84d";ctx.fillStyle="#ffd84d";ctx.beginPath();ctx.moveTo(-10,24);ctx.lineTo(0,48+Math.random()*10);ctx.lineTo(10,24);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#f4f0e7";ctx.strokeStyle="#18132a";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(23,26);ctx.lineTo(0,16);ctx.lineTo(-23,26);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#7657ff";ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.restore()}
function loop(time){const dt=Math.min((time-lastTime)/1000,.04);lastTime=time;update(dt);draw();if(game.running)frame=requestAnimationFrame(loop)}
function steer(e){if(!game?.running)return;const bounds=canvas.getBoundingClientRect(),point=e.touches?.[0]||e;game.player.x=Math.max(32,Math.min(W-32,(point.clientX-bounds.left)/bounds.width*W))}
window.addEventListener("keydown",e=>{keys.add(e.key);if(["ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();if(e.key===" "&&!game?.running)start()});window.addEventListener("keyup",e=>keys.delete(e.key));window.addEventListener("resize",resize);canvas.addEventListener("pointermove",e=>{if(e.buttons)steer(e)});canvas.addEventListener("pointerdown",steer);canvas.addEventListener("touchmove",steer,{passive:true});startButton.addEventListener("click",start);
resize();bestEl.textContent=String(Number(localStorage.getItem("stellar-drift-best")||0)).padStart(6,"0");reset();game.running=false;draw();
